# Generated by Django 4.0.3 on 2022-03-09 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tinyintennesseeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_category_id',
        ),
        migrations.AddField(
            model_name='location',
            name='location_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tinyintennesseeapi.locationcategory'),
        ),
        migrations.CreateModel(
            name='TitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='builder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinyintennesseeapi.tituser'),
        ),
        migrations.AlterField(
            model_name='law',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinyintennesseeapi.county'),
        ),
        migrations.AlterField(
            model_name='location',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinyintennesseeapi.county'),
        ),
        migrations.AlterField(
            model_name='location',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinyintennesseeapi.tituser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinyintennesseeapi.tituser'),
        ),
    ]
