# Generated by Django 4.0.3 on 2022-03-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyintennesseeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
