# Generated by Django 4.0.3 on 2022-03-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyintennesseeapi', '0002_builder_is_approved_location_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='building',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='law',
            name='zoning',
            field=models.CharField(max_length=1000),
        ),
    ]
